config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'application#index'
    resources :seasons
    resources :orders
  end

  resources :orders, only: [:create, :new, :show]
  devise_for :users

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  obfuscate_id
  belongs_to :season
  belongs_to :location
  has_many :order_items, dependent: :destroy
  has_many :items, through: :order_items

  before_save :calculate_total
  after_create :update_inventory

  validates :phone_number, presence: true
  validates :pick_up_date, presence: true
  accepts_nested_attributes_for :order_items, reject_if: :blank_order_item

  private
  def blank_order_item(attributes)
    attributes['item_id'].nil? || attributes['quantity'].nil?
  end

  def calculate_total
    subtotal = order_items.map { |oi| oi.quantity * oi.item.price }.sum
    tax_total = subtotal * location.tax_rate if location.tax_rate
    self.subtotal = subtotal
    self.tax_total = tax_total
    self.total = subtotal + tax_total
  end

  def update_inventory
    total_turkey = order_items.map { |oi| oi.quantity }.sum
    if season.turkeys > total_turkey
      season.decrement!(:turkeys, total_turkey)
    end
    if season.turkeys < 1
      season.update(active: false, end_date: Time.now)
    end
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/season.rb
class Season < ApplicationRecord

  has_many :orders

  scope :active, -> { find_by(active: true) }

  def activate
    update(active: true)
  end

  def date_list=(dates)
    self.pick_up_dates = dates.gsub(/[^\d\/,]/, '').split(',')
  end

  def date_list
    self.pick_up_dates.join(',')
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :recoverable, :rememberable,
    :trackable, :validatable, :lockable
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_action :authorize_admin!
  def index
  end

  private
  def authorize_admin!
    authenticate_user!
    unless current_user.admin?
      redirect_to root_path, alert: 'You are not authorized to do that'
    end
  end
end

app/controllers/admin/seasons_controller.rb
class Admin::SeasonsController < Admin::ApplicationController
  def index
    @seasons = Season.all
  end

  def new
    @season = Season.new
    @options = ["-- Select season --", "Fall #{Date.today.year}", "Winter #{Date.today.year}"]
  end

  def create
    @season = Season.new(season_params)
    if @season.save
      redirect_to admin_root_path, notice: 'Season created'
    else
      flash[:alert] = 'Season failed to save, please try again'
      render :new
    end
  end

  def show
  end

  def edit
  end

  private
  def season_params
    params.require(:season).permit(:name, :turkeys, :start_date, :date_list)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def new
    @season = Season.select(:id, :name, :pick_up_dates).active
    @pick_up_days = @season.pick_up_dates
    @order = Order.new
    @items = Item.select(:id, :name)
    @order.order_items.build
    @locations = Location.pluck(:name, :id)
  end

  def create
    @order = Order.new(order_params)
    if @order.save
      flash[:notice] = 'Order saved!'
      redirect_to @order
    else
      flash[:alert] = 'Order failed to register'
      render :new
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  private
  def order_params
    params.require(:order).permit(:season_id, :location_id, :first_name, :last_name,
      :phone_number, :pick_up_date, order_items_attributes: [:id, :item_id, :quantity])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @season = Season.active
  end
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/admin/seasons_helper.rb
module Admin::SeasonsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/application/index.html.haml
.row
  .col
    %h1 Welcome to the Admin Lounge

    = link_to 'View all seasons', admin_seasons_path, class: 'btn btn-info'
    = link_to 'Add new season', new_admin_season_path, class: 'btn btn-info'

app/views/admin/seasons/edit.html.haml
%h1 Admin::Seasons#edit
%p Find me in app/views/admin/seasons/edit.html.haml

app/views/admin/seasons/index.html.haml
%h1 Admin::Seasons#index
%p Find me in app/views/admin/seasons/index.html.haml

app/views/admin/seasons/new.html.haml
%h1 New season
.row
  .col
    = bootstrap_form_for [:admin, @season] do |f|
      = f.select :name, @options, {}, { class: 'sm-form-element' }
      .start-date-wrapper
        = f.text_field :start_date, class: 'datepicker-autoclose md-form-element hidden'
      = f.number_field :turkeys, label: 'Number of turkeys', class: 'sm-form-element'
      = f.text_field :date_list, class: 'datepicker-multi lg-form-element'
      = f.submit 'Save'

app/views/admin/seasons/show.html.haml
%h1 Admin::Seasons#show
%p Find me in app/views/admin/seasons/show.html.haml

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Turkeys
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.11/jquery.mask.min.js'
  %body
    %nav.navbar.navbar-expand-lg.navbar-light.bg-light.fixed-top.justify-content-between
      = link_to 'Turkeys', root_path, class: 'navbar-brand'
      %form.form-inline.my-2.my-lg-0
        %input.form-control.mr-sm-2{"aria-label" => "Search", :placeholder => "Search", :type => "text"}/
        %button.btn.btn-outline-success.my-2.my-sm-0{:type => "submit"} Search
    .container
      %main
        = yield

app/views/orders/_form.html.haml
.row
  .col-8
    %h1
      New order for
      = @season.name
    = bootstrap_form_for @order do |f|
      = f.hidden_field :season_id, value: @season.id
      = f.select :location_id, @locations
      = f.text_field :first_name
      = f.text_field :last_name
      = f.phone_field :phone_number
      = f.select :pick_up_date, @pick_up_days
      %hr
      - @items.each do |item|
        = f.fields_for :order_items do |ff|
          = ff.hidden_field :item_id, value: item.id
          %h4= item.name
          = ff.number_field :quantity
      = f.submit "Create order", class: 'btn btn-success'

app/views/orders/new.html.haml
= render 'form'

app/views/orders/show.html.haml
.row
  .col-8
    %h2
      Order for
      = "#{@order.first_name} #{@order.last_name}"
    - @order.order_items.each do |oi|
      %h4= oi.item.name
      %span
        Quantity:
        = oi.quantity

app/views/welcome/index.html.haml
.row
  .col-8
    - if @season
      %h1 We got turkeys!
      = link_to 'Place order', new_order_path, class: 'btn btn-lg btn-primary'
    - else
      %h1
        We're sold out for the year.  See you in
        = (Date.current + 1.year).year
        !